### ISSUE TITLE
Issue with time.Time in golden struct

### ISSUE THREAD

**Issue by nmiculinic** [hexops/autogold#17]
This works quite nicely...but I have an issue with structs using time.Time. Namely time.Time has a bunch of private internal variables, which naturally I cannot setup. 

* Can I ignore some fields in the struct? 
* Is there some special handling for time.Time? 

The time is stable since it's coming from the database.

**Comment by rdeusser** [comment]
This `autogold.Equal(t, expected, autogold.ExportedOnly())` should get you what you want.

**Comment by nmiculinic** [comment]
Awesome, this works!
