### ISSUE TITLE
Go modules require a new directory "v2" for v2.0.0

### ISSUE THREAD

**Issue by larschri** [hexops/autogold#35]
It is not possible use go get like this:

    $ go get github.com/hexops/autogold@v2.0.0
    go: github.com/hexops/autogold@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/hexops/autogold/v2")

Please see https://go.dev/blog/v2-go-modules

Expected behavior is that it should be possible to use 'go get' with a version tag, just like it works with the sha:

    go get github.com/hexops/autogold@57e286ce7f6d2f9144e2755638f248be64050c47

**Comment by fabstu** [comment]
Problem might be that go.mod of the v2.0.0 tag does not contain the /v2 prefix.

@slimsag  after adding that to a v2.0.1, try it out with `go get github.com/hexops/autogold/v2`.

**Comment by slimsag** [comment]
Ah that's annoying, sorry about that. Fixed, this works now:

```
go get -u github.com/hexops/autogold/v2
```
