### ISSUE TITLE
Inline test update runs indefinitely

### ISSUE THREAD

**Issue by jamestelfer** [hexops/autogold#36]
For the test:

```go
package main

import (
	"testing"

	"github.com/hexops/autogold/v2"
)

func TestInlineUpdate(t *testing.T) {
	autogold.Expect(nil).Equal(t, "1")
}
```

`go test` fails as expected, and `go test -update` hangs and doesn't exit. I'm running Go 1.19 on MacOS 12.0.1 with an M1 chip and the latest v2 version of Autogold.

I tried this initially in one of my projects and it did the same thing, so I kept trying to simplify the reproduction. Since it's so simple, I suspect I'm doing something wrong: any pointers on how I should further diagnose would be appreciated!

Note that this is inline only: golden files work as expected (see what I did there?).

**Comment by timonwong** [comment]
Same problem here, after debugging, I found it cannot acquire path lock here, in lock.ownership.Lock():

https://github.com/hexops/autogold/blob/76c55ef0f5d77b75d68581453ddd4ee36ab59b4d/autogold.go#L206-L218

**Comment by timonwong** [comment]
Ok, since the `lock.ownership` haven't yet get released, another call try to acquire it during `replaceExpect`

So it's a dead lock


```go
                                 unlock, err := acquirePathLock(testPath)   // >>>>>>>>>> acquire lock
				profAcquirePathLock = time.Since(start)
				if err != nil {
					writeProfile()
					t.Fatal(err)
				}
				defer func() {
					if err := unlock(); err != nil {  // >>>>>>>>>>>>>  defer won't get called before replaceExpect, so the lock is still acquired.
						t.Fatal(err)
					}
				}()

				// Replace the autogold.Expect(...) call's `want` parameter with the expression for
				// the value we got.
				start = time.Now()
                                 // >>>>>>>>>>>>>>>>>>>>>>> replaceExpect tries to acquire same lock, so deadlocked
				_, err = replaceExpect(t, testPath, testName, line, gotString, true)
```
