### ISSUE TITLE
question: testing of a collection of files in a folder as a test

### ISSUE THREAD

**Issue by gedw99** [hexops/autogold#39]
i want to test the output of files to a folder.

My use case is a golang tool that does lots of file manipulation such as renaming.

Does anyone know if autogold can do this ? could not see in code or issues but i only spent a few minutes looking....

**Comment by slimsag** [comment]
You can use `filepath.Walk` or similar to walk the directory and build a string or text document listing the files in the folder, then pass that into autogold for comparison.
