### ISSUE TITLE
`ExpectFile` with `Raw` does not work cross-platform (windows and non-windows)

### ISSUE THREAD

**Issue by iwahbe** [hexops/autogold#51]
`ExpectFile` and `Raw` allow users to compare large objects while keeping the git diff extremely readable. For example:

```go
autogold.ExpectFile(t, autogold.Raw(must(protojson.MarshalOptions{
	Multiline: true,
}.Marshal(msg))))
```

This generates a file such as this:

```js
{
  "inputs": {
    "attrBoolRequired": true,
    "attrIntRequired": 64,
    "attrStringRequired": "s"
  }
}
```

Unfortunately, the `.golden` file fails in CI when tested on windows and a non-windows platform (linux in my case). I assume this is due to platform specific file endings (`\r`).

It would be great if autogold either handled this problem itself or provided an `Option` that allows overriding the comparison so we can address the problem directly.

**Comment by slimsag** [comment]
I would guess this is actually a bug (/feature) in your `protojson` marshal function

testing/knowing whether newlines have changed can often be important

I'd suggest you probably just want to `strings.Replace(theString, `\r`, `\n`, -1)` before feeding it to `autogold.Raw` to address this
